### ISSUE TITLE
Setting up TagUI-Python on Windows 10 - slow downloading of TagUI

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#11]
@kensoh, trying to set up TagUI-Python on my Windows 10 machine.

1. Have run "pip install tagui"

2. Running "pip list" show
```
Package    Version
---------- -------
tagui      1.1.0
```

3. Test script as follows:
```python
import tagui as t
t.init()
t.echo("test123")
t.close()
```

4. Running the above script from command prompt, it shows the following and stops there:
```
[TAGUI][INFO] - setting up TagUI for use in your Python environment
[TAGUI][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[TAGUI][INFO] - C:\Users\username\AppData\Roaming
```

5. If I press Ctrl-C, the following messages appear:
```
[TAGUI][INFO] - setting up TagUI for use in your Python environment
[TAGUI][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[TAGUI][INFO] - C:\Users\username\AppData\Roaming
Traceback (most recent call last):
  File "test2.py", line 2, in <module>
    t.init()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tagui.py", line 359, in init
    if not setup():
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tagui.py", line 208, in setup
    if not download(tagui_zip_url, home_directory + '/' + tagui_zip_file):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tagui.py", line 1092, in download
    import urllib.request; urllib.request.urlretrieve(download_url, filename_to_save)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
```
6. Are there any other settings I need to do to get TagUI-Python running on Windows 10? Is there anything that I've missed?

**Comment by kensoh** [comment]
Hi CK, thanks for the detailed replication steps and error message!

Can you try to let it run for a few minutes to see whether it completes? As the zip file is hosted on GitHub for free, the download rate can be slow and may take a few minutes to complete download.

**Comment by kensoh** [comment]
Adding to above, before you download again, there is now v1.3 which has OCR capability, specifying region of interests, and some improvements - https://github.com/tebelorg/TagUI-Python/releases

To upgrade -
```
pip install tagui --ugprade
```

**Comment by ck81** [comment]
> Adding to above, before you download again, there is now v1.3 which has OCR capability, specifying region of interests, and some improvements - https://github.com/tebelorg/TagUI-Python/releases
> 
> To upgrade -
> 
> ```
> pip install tagui --ugprade
> ```

I've upgraded to v1.3 and let it run overnight last night. It didn't work.

But I tried to re-run it just now, it worked! I see the message ""test123" on the command prompt.

However, when I re-run it again, this time it gives the following error:

~~~
[TAGUI][ERROR] - following happens when starting TagUI...

Fatal: Access is denied; did you install phantomjs?

test123
[TAGUI][ERROR] - use init() before using close()
~~~

Is there a log file somewhere to see which file "Access is denied"?

**Comment by ck81** [comment]
Tried another sample code:
~~~python
import tagui as t
t.init()
t.url('https://www.google.com')
t.type('//input[@class="gLFyf gsfi"]', 'weather singapore[enter]')
temp = t.read('wob_tm')
print("temp = " + temp)
t.close()
~~~

Error message
~~~
[TAGUI][ERROR] - following happens when starting TagUI...

Fatal: Access is denied; did you install phantomjs?

[TAGUI][ERROR] - use init() before using url()
[TAGUI][ERROR] - use init() before using type()
[TAGUI][ERROR] - use init() before using read()
temp =
[TAGUI][ERROR] - use init() before using close()
~~~

**Comment by kensoh** [comment]
For running overnight, is there any error message after below message or it hangs forever? 

```
[TAGUI][INFO] - setting up TagUI for use in your Python environment
[TAGUI][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[TAGUI][INFO] - C:\Users\username\AppData\Roaming
```

**technical reference information**

Below is the URL for the Windows download and the download is done using Python standard module urllib for downloading files. In v1.3 I changed it to output the detailed Python error message if error is encountered while downloading.

https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip

For your other question on access denied error, i'll reply at your other issue #15

**Comment by kensoh** [comment]
Closing this issue as discussion on downloading hangs on Windows continues in https://github.com/tebelorg/TagUI-Python/issues/15#issuecomment-505275241

**Comment by Arcsle09** [comment]
Hi,
I have upgraded tagui and tried to run below code but it is taking a lot of time. 

(base) C:\Users\chra8017>pip install tagui --upgrade                                                                                             Requirement already up-to-date: tagui in c:\users\chra8017\appdata\local\continuum\anaconda3\lib\site-packages (1.26.1) 

In [2]: import tagui as t

In [3]: t.init()
   ...: t.echo("test123")
   ...: t.close()
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\chra8017\AppData\Roaming

I already have a tagui zip file(TagUI_Windows.zip) downloaded. 

Is there a way to skip these instructions and I directly put the unzipped folder to  C:\Users\chra8017\AppData\Roaming?

**Comment by kensoh** [comment]
Hi @Arcsle09 the usual cause for slow downloading is either due to network slowness or company firewall restriction. Trying using a 5GHz wifi to do this and it should be faster (the download endpoint is hosted by GitHub).

However, if there is company firewall policy that is blocking such automated download, you can use the pack() function on your personal computer or a computer that has no such firewall restrictions. After that, there will be a generated zip file for you to copy over and run.

For future upgrades, you can use update() function to generated a Python script with the updated binary data embedded in it, to copy over to the restricted network laptop and run.

https://github.com/tebelorg/RPA-Python#core-functions
