### ISSUE TITLE
Selecting multiple options on webpage - use dom() for complex interactions

### ISSUE THREAD

**Issue by ruturajdev** [tebelorg/TagUI-Python#17]
Dear Ken Soh,

I am facing issue to select multiple options in a box. I am attaching an image of the box. Please suggest me how can do it.
![box](https://user-images.githubusercontent.com/49855122/60177860-9dd33a80-9837-11e9-9c9d-b0d8aa841df7.PNG)

I want to select all options except for the first two as shown in the pic below. Please suggest how to get this done.
![box2](https://user-images.githubusercontent.com/49855122/60177960-dd018b80-9837-11e9-96a3-d98869ea9d4a.PNG)

Thanks in advance.

**Comment by kensoh** [comment]
Hi @ruturajdev this looks difficult to select and I will need to try out myself to find out if there is a good way to do the selection. Do you have the replication steps and webpage URL to reach this screen?

**Comment by ruturajdev** [comment]
Hi @kensoh following is the webpage URL where we have to make the selection

https://www.camsonline.com/DistributorServices/COL_Mailbackservice.aspx

**Comment by kensoh** [comment]
There can be other creative solutions, such as using vision() to send custom SikuliX command to hold down Control key and then doing click() with visual automation or web selector. But if I am to automate this, I'll use simple JavaScript to do that. Example below using dom() to send JS code to webpage -

```py
>>> import tagui as t
>>> t.init()
>>> t.url('https://www.camsonline.com/DistributorServices/COL_Mailbackservice.aspx')
True
>>> t.dom('combo_box = document.getElementById("ddlamc")')
''
>>> t.dom('return combo_box.options[3].text')
'H \\ HDFC Mutual Fund'
>>> t.dom('combo_box.options[3].selected = true')
''
>>> t.dom('combo_box.options[5].selected = true')
```

**Comment by kensoh** [comment]
Closing issue for now, but do post here if run into any problem with this combo box!

**Comment by ruturajdev** [comment]
Hello @kensoh,

Thanks a lot. I'm able to make the selections.
