### ISSUE TITLE
Automation example - RedMart rescheduling order (cancel & add again)

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#24]
**UPDATED - version 2 with browser prompt for URL, and handles multiple quantity per item**

Whenever there is a need to reschedule our groceries delivery order on RedMart, there is a need to cancel the order and then manually add back the items one by one to create a new order.

My wife is very frustrated with that, because in between clicks there is so much waiting time, and the UI cannot ctrl + click to open in new tabs to do this. So I wrote below automation script in 15 minutes for her. Now she can double-click on this script and automate it herself. Share here as well!

![Screenshot 2019-07-12 at 6 22 18 PM](https://user-images.githubusercontent.com/10379601/61121700-6f5d8c80-a4d2-11e9-9a66-edb14a64a8c9.png)

```py
import tagui as t
t.init()

# get URL of old groceries order to re-add every items to cart
t.url(t.dom('return prompt("Paste the URL of your groceries order and login to RedMart")'))

# set a maximum 5-minute timeout for user to login to RedMart
t.timeout(300)

if not t.exist('(//*[@class="order-item"])[1]//*[@class="item-pic"]'):
    t.dom('alert("Quitting as groceries order page is not detected after 5 min. Bye!")')

# change back to default of 10 seconds to quit fast on error
t.timeout(10)

# get count of total items to place order for
total_items = t.count('//*[@class="order-item"]//*[@class="item-pic"]')

# to track total quantity of items to order
total_quantity = 0

for item in range(1, total_items + 1):
    # get count of quantity to order for item, before clicking into item
    item_quantity = int(t.read('(//*[@class="order-item"])['+ str(item) + ']//*[@class="item-quantity"]//*[@class="text"]'))
    t.click('(//*[@class="order-item"])[' + str(item) + ']//*[@class="item-pic"]')

    # first click ADD TO CART, then click + icon for subsequent quantity
    t.click('ADD TO CART')
    for more_quantity in range(item_quantity - 1):
        t.click('next-icon-add')

    # wait to ensure adding of item has been registered before going back
    t.wait(3)
    total_quantity = total_quantity + item_quantity
    t.dom('history.back()')
    t.wait(3)

# show popup with summary of the item and quantity count before exiting
t.dom('alert("' + str(total_items) + ' items (total quantity of ' + str(total_quantity) + ') have been added to cart. Bye!")')
t.close()
```

**Comment by kensoh** [comment]
Adding on, wait() is usually not necessary as there is auto-wait for UI elements to appear until timeout.

For above, it is to ensure that the click has been processed by the webapp (seems to have some lag) before proceeding, and that previous page items have been fully loaded before proceeding.

**Comment by kensoh** [comment]
Updated above version 2 with browser prompt for URL, and handles multiple quantity per item

**Comment by kensoh** [comment]
Closing issue as this example is now added to readme under API reference section.

**Comment by CL545740896** [comment]
[TAGUI][ERROR] - 'utf-8' codec can't decode bytes in position 44-45: invalid continuation byte  ,I think u should support   utf-8  , Chinese  example

**Comment by kensoh** [comment]
Can you paste the Python code that cause this error message so that I can check?

In this issue https://github.com/tebelorg/TagUI-Python/issues/14 the package has switched over to use UTF-8. Not sure of the cause, it could be that webpage you are accessing has non-UTF-8 characters. Wait for your code to check further. Also, I assume you are using new version of the package `t.__version__` should be > 1.4 for UTF-8.

**Comment by sunnyhemnani** [comment]
Hey @kensoh 
Can you please tell me how to set TagUI up on Production (Live Server)?
Thank you.

**Comment by kensoh** [comment]
Hi @sunnyhemnani the setup instructions for this package is here -
https://github.com/tebelorg/RPA-Python#rpa-for-python-snake

Just `pip install rpa`, you will need Python install on the server.

If you are referring to the TagUI RPA software instead of this Python package,
refer to this setup steps - https://github.com/kelaberetiv/TagUI#set-up

**Comment by sunnyhemnani** [comment]
@kensoh  I want to know the basic Server specifications for TagUI RPA software?
I have a droplet on the Digital ocean!

**Comment by kensoh** [comment]
A basic Windows, Linux or macOS operating system will be able to run TagUI or RPA for Python.

**Comment by yeders** [comment]
is there a way to set an active chrome window or by title, as the working window for the RPA bot to work with?

It seems that when it launches the URL, its in a slim incognito window - If i'm working in a secured/ login page or one that is only accessible via another portal, then it requires a bit of running around to get there each time I want to use the bot.

thanks

**Comment by kensoh** [comment]
Hi @yeders to do that you can use visual automation, and do a click() on the taskbar / docking bar to click on the Chrome icon to make it in the foreground. You can also try simulating [ctrl][tab] (Windows) or [cmd][tab] (Mac) using keyboard() and keep repeating until Chrome window is in front (use hover() to check for some unique thing on the screen to tell that it is ready).

**Comment by ringomass** [comment]
If i use href to get part of the address link, which method is used

**Comment by kensoh** [comment]
For reading attributes of a web element, the syntax is using `r.read('XPath/@href')`

**Comment by ringomass** [comment]
![image](https://user-images.githubusercontent.com/72288271/120911738-4b098b00-c6bc-11eb-8dd0-7294d5da3b93.png)
![微信截图_20210606114250](https://user-images.githubusercontent.com/72288271/120911753-72f8ee80-c6bc-11eb-9d85-a401a2220e08.png)
![微信截图_20210606114259](https://user-images.githubusercontent.com/72288271/120911762-7be9c000-c6bc-11eb-95fd-6c9c1af4806d.png)
Do I need to write the full address of the href here? If so, can I use a regular expression, because herf is dynamic

**Comment by kensoh** [comment]
Hi @ringomass, I assume that you want to read the URL for use later. In that case, first find a good way to point to the item, eg some XPath. After that then do `r.read('XPath/@href')`.

You can try google more on XPath to see how to write XPath, or try using the Chrome inspector to copy out the XPath - https://tagui.readthedocs.io/en/latest/faq.html#how-do-i-find-the-xpath-of-a-web-element

Above website doesn't look like public can access so I can't try it.
