### ISSUE TITLE
Running TagUI-Python for Windows / desktop apps without Chrome

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#27]
In #25, you commented that:

> There are also major advantages of TagUI for Python over a number of Python packages for
> digital automation. Some of them can only automate webapps, some can only automate 
> keyboard + mouse. But this tool can do all, plus ability to automate using computer vision and
> extract info using OCR, all within one seamless API 

Currently in TagUI-Python, when one issues `t.init()`, it will open a new empty chrome window.

For windows/desktop apps, or if the user only want to automate keyboard + mouse, the empty chrome window will "confuse" the user, or even block the windows/desktop app required for image-based recognition.

Possible to have the same behaviour as that of TagUI i.e. a new chrome window will only appear at the first initiation of http://

**Comment by kensoh** [comment]
Oh similar behaviour is possible with TagUI for Python, the init() function has following parameters and defaults - `init(visual_automation = False, chrome_browser = True)`. That means without parameters, visual_automation will be off and chrome_browser will be on. To do that you can use -

`t.init(True, False)` or `t.init(visual_automation = True, chrome_browser = False)`

So Chrome won't be launched (similar to running TagUI without chrome option). Python lets users set parameters just by the value (in order of the parameters definition) or by explicitly specifying which parameter you want to set and the value. More on init() function and friends -

https://github.com/tebelorg/TagUI-Python#core-functions

**Comment by ck81** [comment]
That's cool, Ken. You've all these thought out!
