### ISSUE TITLE
Is waiting for fractions of a second possible? Eg t.wait(2.5) - yes!

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#28]
Hi Ken,

I see from your sample code https://github.com/tebelorg/TagUI-Python#use-cases
> t.wait(2.5)

In TagUI, I thought the `wait` supports only integer.

In TagUI-Python, it now supports floating point like 2.5 seconds?

Also, can I use python's sleep function in TagUI-Python script? Are there any differences?

~~~python
import time
time.sleep( 5 )
~~~

**Comment by kensoh** [comment]
Yes, both TagUI and this project TagUI for Python supports fraction of seconds. It wasn't shown in the TagUI documentation but demoed in the sample workflows using wait step for X.Y seconds.

Yes you can use Python's sleep function. There is no difference. The only difference will be you will have to do the `import time` yourself, and also explicitly include the number of seconds. For t.wait(), if no parameter is given, it will default to 5 seconds, similar to TagUI behaviour.
