### ISSUE TITLE
TagUI for Python OCR Findings, Tips and References

### ISSUE THREAD

**Issue by brandybaby** [tebelorg/TagUI-Python#29]
Hi @kensoh, while doing research and testing on OCR, I found that TagUI-Python is extremely functional in this aspect. It is able to carry out OCR on webpage images (t.url -> t.read) and local images as well (using visual_automation = True, chrome_browser = False -> reading using coordinates).

I also researched and learned that there is a TagUI RPA Studio, her OCR is more user friendly as users do not need to use t.mouse_xy() to find the coordinates. Also Kantu's OCR is also able to detect images and do search and verification, which could possibly be added into TagUI-Python in the future.

**Comment by kensoh** [comment]
Thanks @brandybaby for sharing your findings!

For TagUI Studio, are you referring to the project by Murat Cim? He'll be changing the name soon as the Apache 2.0 license has restriction on the naming. It's a cool app where he combine TagUI and custom Python code to implement new features.

For TagUI or TagUI for Python, as there is no graphical IDE, mouse_xy() is used to find the coordinates. Alternatively, 3rd-party tools can be used to see the current coordinates of mouse cursor. For eg on macOS, command + shift + 4 will open up a cross-hair showing current coordinates of mouse cursor.

Kantu's OCR is web-based for the free version and paid for the local enterprise version. There should be negligible difference in accuracy as Kantu's OCR and TagUI's OCR (through SikuliX's integration) is based on Tesseract. But if there are features other OCR tools have that can be practically implemented into TagUI, let me know!

Functions such as t.hover(), t.present(), t.exist() can be used to search for an UI element visually. Also, functions such as t.click() can take an image input to search for the UI element to click.

**Comment by kensoh** [comment]
Adding below paragraphs from [project readme](https://github.com/tebelorg/TagUI-Python#api-reference) which is related to visual automation / OCR.

For reference by users who search for OCR topic in future -

>An element identifier can also be a .png or .bmp image snapshot representing the UI element (can be on desktop applications or web browser). x, y coordinates of elements on the screen work as well. Transparency (0% opacity) is supported in .png images, for eg using an image of an UI element with transparent background to enable clicking on an UI element that appears on different backgrounds on different occasions.
>
>A further example is an image of the window or frame (PDF viewer, MS Word, textbox etc) with the center content of the image set as transparent. This allows using read() and snap() to perform OCR and save snapshots for application windows, containers, frames, textboxes with varying content. Also for read() and snap(), x1, y1, x2, y2 coordinates pair can be used to define the region of interest on the screen to perform OCR or capture snapshot.
