### ISSUE TITLE
I can't get XPath - user solved by using visual automation instead

### ISSUE THREAD

**Issue by joaoauvs** [tebelorg/TagUI-Python#320]
I can't click on the >> element or get the frame from any part of this screen. I've already mentioned it from top to bottom.

Site: https://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?jornal=515&pagina=11&data=21/10/2021

![image](https://user-images.githubusercontent.com/58301591/138774037-5e8e0980-5401-4532-924f-bffccb5c650c.png)

**Comment by kensoh** [comment]
Adding on, from above error message it suggests that the wrong syntax might be used. The correct syntax is `r.frame('controlador')`, don't have to specify the whole XPath with `r.frame('/*[@name="controlador"]')`. But yes, visual automation is the straightforward way to solve this problem!
