### ISSUE TITLE
Using dom() with variables from Python environment

### ISSUE THREAD

**Issue by ck81** [tebelorg/TagUI-Python#49]
Hi Ken,

In TagUI sample folder '9_misc', you have the following sample code:
```javascript
dom_json = '#header p'
dom return document.querySelector(dom_json).innerText
echo 'dom_result using 1 dom_json variable - ' dom_result
```

May I know what is the corresponding code in TagUI-Python?

How do we pass in that `dom_json`?

I suppose you will return `dom_result`, so we do not need this.

**Comment by ck81** [comment]
How about the following code also from the same file:
```javascript
element1 = '#header p'
element2 = '#footer'
// JavaScript syntax to create object and assign variables to children
dom_json = {element1: element1, element2: element2}
dom return document.querySelector(dom_json.element1).innerText
echo 'dom_result using multiple dom_json variables - ' dom_result
dom return document.querySelector(dom_json.element2).innerText
echo 'dom_result using multiple dom_json variables - ' dom_result
```

**Comment by kensoh** [comment]
Hi CK, during the implementation for TagUI for Python, I didn't think there is a need for dom_json to pass in variables from Python environment to the browser DOM for use, because variables can be evaluated within Python before being passed on to TagUI. Below is example for above -

**In TagUI**
```js
dom_json = '#header p'
dom return document.querySelector(dom_json).innerText
echo 'dom_result using 1 dom_json variable - ' dom_result
```

**In TagUI for Python**
```py
dom_variable = '#header p'

# double-quote the string
dom_result = t.dom('return document.querySelector("' + dom_variable + '").innerText')

# single-quote the string
dom_result = t.dom('return document.querySelector(\'' + dom_variable + '\').innerText')
this.echo('dom_result using 1 dom variable - ' + dom_result)
```

In TagUI, something like above Python implementation will be hard to do correctly in a natural way.

**Comment by kensoh** [comment]
From TagUI to the browser DOM, both of them are in JavaScript, so multi-parameters data structure can be passed using dom_json. From TagUI for Python to browser DOM, it is from Python to JavaScript. So, users can use something like above to pass in multiple variables -

```py
element1 = '#header p'
element2 = '#footer'
t.echo(t.dom('return document.querySelector("' + element1 + '").innerText'))
t.echo(t.dom('return document.querySelector("' + element2 + '").innerText'))
```

Defining complex data structures in JavaScript in the browser DOM is also possible, by using above method to evaluate the variables in Python first and concatenate the full statement, before passing to the browser using dom(). Below is an example. But probably you won't need to do this.

```py
element1 = '#header p'
element2 = '#footer'
t.dom('variable_in_browser_dom = {element1: "' + element1 + '", element2: "' + element2 + '"}')
t.echo(t.dom('return variable_in_browser_dom.element1'))
t.echo(t.dom('return variable_in_browser_dom.element2'))
```

**Comment by ck81** [comment]
Hi Ken,

Thanks for the sample code for using `dom()`.

Just want to let you know that the `dom()` command is another feature that really differentiates your TagUI/TagUI-Python from other RPA tools.

Your TagUI makes it easy to issue any dom() commands.  There are some websites in which TagUI `click()` does not work, but using javascript `click()` command work.
