### ISSUE TITLE
Code ran successfully but mouse did not respond - pending logs and replication

### ISSUE THREAD

**Issue by woshilaowanga** [tebelorg/TagUI-Python#526]
![Snipaste_2024-04-24_17-06-12](https://github.com/tebelorg/RPA-Python/assets/152626351/ef84cefb-7934-4519-ac65-937d865729b6)
There was no change, only a true was returned

**Comment by kensoh** [comment]
Hi @woshilaowanga, that is unexpected, can you try the following?

1. run with r.debug(True) and share the rpa_python.log
2. do something like r.click('image.png') to see if the visual automation engine is working (image.png can be image screenshot of something on your screen)
3. check the folder r.tagui_location() --> tagui or .tagui folder --> src --> tagui.sikuli --> share the logs there here

**Comment by kensoh** [comment]
(closing issue for now, but will look out for your reply if any)
