### ISSUE TITLE
Where to store image files for visual automation? - same folder as script

### ISSUE THREAD

**Issue by onenessboy** [tebelorg/TagUI-Python#54]
HI

Can you please let me know where should I save snipped images for visuation automation in while using this in python ? In original tagui, i saved all images in tagui.sikuli directory . Where should i save here while using this respository ?

and also do i need to specify any code to initiate visual automation when I use this python tagui ?

**Comment by kensoh** [comment]
Hi for TagUI for Python, please raise issues at that GitHub page, as it is a separate project and issues for the Python packages should be raised there. General comments -

For image snippets for original TagUI project, you can place images in the same folder as the script. When you do a `click abc.png`, TagUI will automap the path name to the script folder and pass that to SikuliX for usage.

For TagUI for Python, this is also the same, put in the same folder as the script, or where you launch the Python interactive mode, or location of the Jupyter notebook (same location as when your launch jupyter notebook).

To use visual automation, just do `t.init(True)`, there is documentation and examples at the TagUI for Python page. Same for original TagUI, there is no need to save the images tagui.sikuli folder, unless you are writing custom SikuliX commands using vision step or t.vision().

For Windows, location of installation is %APPDATA%\tagui and for macOS / Linux it is in ~/.tagui folder.

**Comment by onenessboy** [comment]
need one more help, i am trying to select copy option from context menu...but i am not able to do so...using visual automation ? any command which can help ? or what is command for cntrl c ? I am using this but not working...t.keyboard('[cntl]c') its not copying
what i am trying to go particular x y position and then press control c.. 
please help

**Comment by kensoh** [comment]
Closing this issue as @onenessboy has raised this new question at #55
