### ISSUE TITLE
Use Control+C or context menu option selection in visual automation?

### ISSUE THREAD

**Issue by onenessboy** [tebelorg/TagUI-Python#55]
need one more help, i am trying to select copy option from context menu...but i am not able to do so...using visual automation ? any command which can help ? or what is command for cntrl c ? I am using this but not working...t.keyboard('[cntl]c') its not copying
what i am trying to go particular x y position and then press control c..
please help

**Comment by kensoh** [comment]
One way is to take an image of the context menu and make sure the 'Copy' text is in the middle of the image. But a more robust way is to use Control+C. The keywords are listed below -

https://github.com/tebelorg/TagUI-Python#pro-functions

For Windows, copying is Control+C, so use `t.keyboard('[ctrl]c')`. For macOS, copying is Command+C, so use `t.keyboard('[cmd]c')`.

There is an upcoming new feature in original TagUI project - the clipboard() helper function. With that, users will be able to put text and get text from the clipboard in their script directly for processing, and make new types of workflows possible.

**Comment by kensoh** [comment]
Closing issue for now but let me know if there's any issues!

The clipboard() helper function will be implemented today, which opens up new use possibilities.

**Comment by onenessboy** [comment]
Hey Ken, thank for that...by the way, I directly import tagui from pycharm IDE.. so what is required upgrade this clipboard function to my existing setup  just a pin install upgrade tagui  and reimport tagui into python environment ?

**Comment by kensoh** [comment]
Ok it's implemented. Yes that should work. To verify, after doing the pip and then import again, you can check `t.__version__` - it should be '1.12.1'. This clipboard() function can be very useful.
