### ISSUE TITLE
Can I change working directory halfway - yes just implemented [done]

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#62]
Raising a pre-emptive issue, for users with edge cases that requires changing current working directory halfway after launching TagUI for Python. Originally reported in #60.

**Comment by kensoh** [comment]
Changing the working directory halfway after TagUI for Python is launched will cause it to hang.

Try changing the current working directory before you do t.init() and it should work. For example the following works. The root cause is TagUI for Python looks for an internal file at the current working directory (the location when it was launched). If the folder changes halfway, TagUI for Python will keep looking for the internal I/O file at the new current working directory. 

But that file is not there, because the TagUI process is still writing to the original folder on launch. It is possible to modify code to handle the edge case of changing working directory halfway, but because that code section will impact all the main use cases, I'll not make this change for now, but raise this issue with a question and answer so that people changing directory halfway and hangs will know why.

```py
import os
import tagui as t

# folder changed before invoking TagUI
os.chdir('test')

t.init()
t.url('https://github.com/tebelorg/TagUI-Python')
t.click('Clone or download')
t.click('Download ZIP')
t.wait()
t.close()

# zip file downloaded to the changed folder 'test'
# instead of the original Python script folder
```

**Comment by kensoh** [comment]
**reference - line to change in tagui.py**
```py
tagui_output_file = _py23_open('tagui_python.txt', 'r')
```

**Comment by kensoh** [comment]
Don't think avoiding a challenge is good spirit, will figure out if there's a way to do this without risking existing users' scripts compatibility and behaviour.

**Comment by kensoh** [comment]
Re-opening issue as feature. The package was not originally designed for the use case of changing current working directory halfway, after initialising and loading TagUI in the background.

**Comment by kensoh** [comment]
Verification scripts used -

**folder changed before invoking TagUI**
```py
import os
import tagui as t

# folder changed before invoking TagUI
os.chdir('test')

t.init()
t.url('https://github.com/tebelorg/TagUI-Python')
t.click('Clone or download')
t.click('Download ZIP')
t.wait()
t.close()

# zip file downloaded to the changed folder 'test'
# instead of the original Python script folder,
# and log file in 'test' deleted after closing
```

**folder changed after invoking TagUI**
```py
import os
import tagui as t

t.init()
t.url('https://github.com/tebelorg/TagUI-Python')

# folder changed after invoking TagUI
os.chdir('test')

t.click('Clone or download')
t.click('Download ZIP')
t.wait()
t.close()

# zip file downloaded to original Python script folder
# as the folder change is made after init() and url(),
# and log file in original folder deleted after closing
```

**And original sample.py script** - https://github.com/tebelorg/TagUI-Python/blob/master/sample.py

**Comment by kensoh** [comment]
Implemented in v1.13, and now available with `pip install tagui --upgrade`

**Comment by yangliu8912** [comment]
Hi Ken,

Thank you so much for adding this feature. I upgraded and it is working for me now!
I can take a break now while TagUI is working hard to download my files, LOL. 
TagUI made my life so much easier : )
Respect!

Best regards,
Yang Liu

**Comment by kensoh** [comment]
Thanks Yang Liu for raising this! Otherwise I would not have known about this.

I was initially thinking not to support this, because it may cause issues with the primary use case of not switching directories halfway. But I think I have to step up to the challenge - I assume this use case would also be common for the work of data scientists and machine learning engineers. 

So I wrote quite a number of lines of code to do this, while minimising risk of primary use case.

I'm happy to hear your feedback, and hope other users have positive experiences like you!

Kind Regards,
Ken Soh
