### ISSUE TITLE
t.keyboard() not working in Mac - Java access issue after OS update

### ISSUE THREAD

**Issue by alakaiobito** [tebelorg/TagUI-Python#66]
Hello Ken,

t.keyboard('[enter]') is not working in Mac. I had enabled visual_automation = True.
But execution gets paused at t.keyboard.

Thanks in advance.

Kind regards,
Alakai

**Comment by kensoh** [comment]
Hi Alakai,

The visual automation mode requires Java JDK 64-bit to work. The program will prompt user to install Java if it is not already installed.

To further check on this issue, do a t.debug(True) before running t.keyboard() to see if there is any special error message. Next, check the following file to see what error is returned by the visual automation engine (~ is the /Users/username folder) -

~/.tagui/src/tagui.sikuli/tagui.log

Kind Regards,
Ken

**Comment by alakaiobito** [comment]
Hello Ken,

I'm getting the following logs:
listening for inputs
keyboard [enter]
listening for inputs

but it's not clicking. 
Am i doing something wrong?

Kindly help.

Kind regards,
Alakai

**Comment by kensoh** [comment]
Have you check above thing to check?

The following file to see what error is returned by the visual automation engine (~ is the /Users/username folder), ~/.tagui/src/tagui.sikuli/tagui.log

**Comment by kensoh** [comment]
Also, if you are at the Python interactive mode or Jupyter notebook, the `t.keyboard('[enter]')` will be at your Python terminal and notebook, not at your application. Because the application focus is on your Python terminal and notebook.

**Comment by kensoh** [comment]
Lastly, provide your minimum replication script and how you run it, so that I can see how to replicate the issue you are facing. For me the following script when I `python demo.py`

demo.py
```py
import tagui as t
t.init(True, False)
t.keyboard('123')
t.keyboard('[enter]')
t.keyboard('456')
t.close()
```

Will give the following output where 123 is typed and 456 is entered onto the next line -
```
$ python3 demo.py 
123
456
```

**Comment by alakaiobito** [comment]
Hello Ken,

The issue was I hadn't enabled java to access my computer. After the OS update, security levels were maxed. Now when I ran your code, pop-up came to enable to java. Now it's working.

I have one other query regarding the keyboard actions. Like you said, if I'm in the notebook, it presses enter in the notebook. is there any way i can do it only in the browser.

Kind regards,
Alex

**Comment by kensoh** [comment]
Hi Alex, I see.. Got it 👌

Thanks for sharing the solution, I haven't come across this Java access issue before.

Yes it can be done, you can add in a `t.click('chrome.png')` before you do the keyboard action. You can do a snapshot of the Chrome icon on your docking bar and save it as chrome.png. By doing a click beforehand, you will bring the application focus to be in Chrome.
