### ISSUE TITLE
page_html = t.read('page') doesn't give the actual html code - use dom()

### ISSUE THREAD

**Issue by alakaiobito** [tebelorg/TagUI-Python#68]
Hello Ken,

page_html = t.read('page') doesn't provide the actual html tree. 
If you take the example of www.youtube.com, the result in page_html is not same as the actual html tree as you can see in developer options.

Kindly help me to get the actual html code.

Kind regards,
Alakai

**Comment by kensoh** [comment]
Hi Alex,

TagUI uses the following JS code to get the full HTML of the webpage.

```
return document.documentElement.outerHTML
```

I'm not a web developer to advise what JavaScript code can return the actual HTML code you want. If you google and find out what it is, you can using the following (replace the JS code below with the code that you want to use to retrieve the actual HTML tree) - 

```
page_html = t.dom('return document.documentElement.outerHTML')
```

**Comment by kensoh** [comment]
Closing issue for now until further inputs, but do share what works for you here!
