### ISSUE TITLE
How to open a PDF filepath in Adobe Reader? - replicate manually or shortcut

### ISSUE THREAD

**Issue by Chao-Jen** [tebelorg/TagUI-Python#69]
Say, I have a PDF file at c:\temp\file.pdf. What I like to do is to open it in Adobe Reader and then ctrl-a, ctrl-c, and save it to a python variable. I saw examples on how to send ctrl-a and ctrl-v, but I can't figure out how to open the file in Adobe Reader.

**Comment by kensoh** [comment]
Hi @Chao-Jen you can try to think through how you will do it manually. Would it be searching for the file by typing, or browsing some file explorer etc. Then you can try to replicate that series of steps using the various functions such as click() or keyboard().

There are also OS-specific ways to do this. For example, macOS has an open command from the terminal. Using `t.run('open filename.pdf')` will open it with the PDF reader. For Windows there may be some similar command to do this the 'shortcut' way.

From below thread, it seems like simply specifying the filename will open it up. So maybe you can try `t.run('c:\\temp\\file.pdf')` or `t.run('your_pdf_viewer.exe c:\\temp\\file.pdf')` to see if that works.

https://superuser.com/questions/246825/open-file-from-the-command-line-on-windows

**Comment by kensoh** [comment]
Closing issue for now until further inputs, but do share what works for you here!
