### ISSUE TITLE
Visual automation on Remote Desktop server - pending checks and logs

### ISSUE THREAD

**Issue by onenessboy** [tebelorg/TagUI-Python#72]
Hi,

What i used is python tagui project.

pip install tagui

Simple program i wrote to test it

import tagui as t
t.init(visual_automation = True, chrome_browser = False)
t.click('start-menu-common.PNG')
t.type('page.png','powerpnt[enter]')

this is script I am directly trying on RDP machine

As per google when you launch RDP from 100 % magnifcation, same magnification will be assgined to targe RDP session also. I see icons are same size as my local laptop 

but some how, when i run program within in RDP it clicking somewhere else 

do you see if windows server behaves differenlty. I am sure target machine is also at 100 % magnification

**Comment by kensoh** [comment]
Have you tried the steps mentioned in #70 -

>You can try developing a simple automation script directly on your remote desktop server and see if that works. If it does not work, check the visual automation engine logs. For windows, It is in the following folder -
>
>%APPDATA%\tagui\src\tagui.sikuli (%APPDATA% is usually C:\Users\Username\Appdata\Roaming)

Capture the image snapshots directly on your remote desktop server, but from your laptop through a RDP session. Ie, use the snipping tool from your remote desktop start menu, instead of the one on your laptop. Try if that works. If can't work, check the logs as mentioned above.

**Comment by onenessboy** [comment]
Hi Kenshoh, 

I tried all your steps above mentioned i mean entire testing remote desktop only (Including screenshot)

But it clicks on little bit higher place on screen , where start menu will be in bottom of any screen


the log shows like this 

[tagui] START  - listening for inputs

[tagui] INPUT  - [1] present C:/PythonProjects/ab/start-menu-common.PNG
[tagui] ACTION - present C:/PythonProjects/ab/start-menu-common.PNG
[tagui] OUTPUT - [1] SUCCESS

[tagui] INPUT  - [2] click C:/PythonProjects/ab/start-menu-common.PNG
[tagui] ACTION - click C:/PythonProjects/ab/start-menu-common.PNG
[log] CLICK on L[30,1060]@S(0) (1047 msec)
[tagui] OUTPUT - [2] SUCCESS

**Comment by kensoh** [comment]
I see.. Try changing the screen resolution on the server to 100% zoom or 125% zoom to see if that works. Sometimes the zoom resolution used is not the default one, the visual automation engine (SikuliX) will be confused and click on the x,y coordinates that are in the wrong resolution.

**Comment by kensoh** [comment]
Above code looks good and the log looks correct. So maybe sometime happening on the visual automation engine layer, due to the screen resolution zoom %. Try above suggestion.

**Comment by onenessboy** [comment]
Hi ken,

so I found it is issue of window remote desktop... now i got new windows remote server where its clicking on right areas but we got new issue which is very strange

New issue:
Mouse pointer is very slow moving where actions are taking place before cursor moves there..
this is only issue i see now.. can you suggest ? I have set mouse pointer speed to full on remote server..

This weird issue..

**Comment by kensoh** [comment]
Hi @onenessboy so far no other users have encountered this strange issue. The only suggestion I have is to try to have access to the remote desktop yourself, and then run the automation to see if there is some problem causing the mouse to move slowly.

My guess is if you access the desktop directly there won't be this problem, but maybe there is some bug in the program you use to connect to the server which shows a lag and slowness in the mouse cursor movement.
