### ISSUE TITLE
User automation script sample on sending email with gmail by @Avikrit10

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#76]
User @Avikrit10 raised a PR on a script written to send email through gmail. Raising an issue to share here, as the PR of the Python script can't really be merged anywhere.

**Comment by kensoh** [comment]
The PR is https://github.com/tebelorg/TagUI-Python/pull/75 and below is the script -

```py
# -*- coding: utf-8 -*-
 """
 Created on Tue Oct 22 21:25:07 2019

 @author: avikr
 """

 import tagui as t
 import getpass
 t.init(visual_automation = True, chrome_browser = True)
 t.url('https://accounts.google.com/ServiceLogin/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin')
 t.wait(10)
 if t.present('//*[@id="identifierId"]')==True:
     t.keyboard('[alt][tab]')
     t.wait(4)
     emailid=t.ask("Enter Email ID")
     t.wait(10)
     t.keyboard('[alt][tab]')
     t.wait(2)
     t.type('//*[@id="identifierId"]',emailid)
     t.wait(3)

     t.click('//*[@id="identifierNext"]/span/span')
     t.wait(3)
     t.keyboard('[alt][tab]')
     t.wait(4)
     password = getpass.getpass("Enter Password")
     t.wait(10)
     t.keyboard('[alt][tab]')
     t.wait(2)
     t.type('//*[@id="password"]/div[1]/div/div[1]/input',password)
     t.wait(3)
     t.click('//*[@id="passwordNext"]/span/span')
 t.wait(25)
 t.keyboard('[tab]')
 t.wait(3)
 t.keyboard('[esc]')
 t.wait(3)   
 t.keyboard('[tab]')
 t.wait(3)
 t.keyboard('[esc]')
 t.wait(3)   
 if t.present('//*[text()="Compose"]')==False:
     t.close()
 t.click('//*[text()="Compose"]')
 t.wait(7)
 t.type('//*[@name="to"]','avikrit10@gmail.com[enter]')
 t.wait(2)
 t.click('//*[text()="Cc"]')
 t.wait(2)
 t.keyboard('avikrit@hotmail.com')
 t.wait(3)
 t.type('//*[@name="subjectbox"]','TagUI[enter]')
 t.wait(2)
 if t.present('//div[@aria-label="Message Body"]')==False:
     t.close()
 t.click('//div[@aria-label="Message Body"]')
 t.wait(4)
 message='''Enter your message

         '''
 t.keyboard(message)
 t.wait(10)

 if t.present('//*[text()="Send"]')==False:
     t.close
 t.click('//*[text()="Send"]')
 t.wait(10)
 t.close()
```

**Comment by sairamphp** [comment]
this is my tagui file I'm unable to send mail please help me.

https://www.gmail.com/
if present('//*[@id="identifierId"]')
{
click //*[@id="identifierId"]
type //*[@id="identifierId"] as `'ex@gmail.com'`
click //*[@id="identifierNext"]/div/button
wait 3
click //*[@id="password"]/div[1]/div/div[1]/input 
type  //*[@id="password"]/div[1]/div/div[1]/input  as `'your password'`
click //*[@id="passwordNext"]/div/button
wait 5
click //*[@class="T-I T-I-KE L3"]
wait 2
click //*[@name="to"] 
type //*[@name="to"] as `'ex@gmail.com'` 
click //*[@name="subjectbox"] 
type //*[@name="subjectbox"] as `'testing'`
click //*[@class="gmail_default"]
type  //*[@class="gmail_default"] as `'tagui testing'`
type  //*[@class="gmail_default"] as `'tagui testing'`
upload .bAK>input[type="file"] as abc.txt 
wait 10 
if present('//*[text()="Send"]')
{
	click //*[text()="Send"]
}
else
{
 click //*[text()="Send"] 
}
}
else
{
wait 5
click //*[@class="T-I T-I-KE L3"]
wait 2
click //*[@name="to"] 
type //*[@name="to"] as `'ex@gmail.com'` 
click //*[@name="subjectbox"] 
type //*[@name="subjectbox"] as `'testing'`
click //*[@class="gmail_default"]
type  //*[@class="gmail_default"] as `'tagui testing'`
upload .bAK>input[type="file"] as abc.txt
wait 10 
if present('//*[text()="Send"]')
{
	click //*[text()="Send"]
}
else
{
 click //*[text()="Send"] 
}
wait 10
}

**Comment by kensoh** [comment]
Hi @sairamphp, for sending emails there are 2 ways.

One way is using the computer vision method which is easier. You specify image snapshots where to click and send email. See below example using TagUI in human language. The concept is the same -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail#dbscom--gmail---download-forex-rates-and-email-download-template

The second way is using what you have reused from @avikr example. I don't think the code is updated to work correctly. You can use a tool like SelectorsHub Chrome extension to pick out the XPaths to be used in your automation. Also, feel free to join the Telegram group to ask any questions. There may be experienced users there who can share on this topic.

https://t.me/rpa_chat
