### ISSUE TITLE
Dealing with iframes - use frame(id or name) and frame() to switch context

### ISSUE THREAD

**Issue by alakaiobito** [tebelorg/TagUI-Python#77]
Hello Ken,

How can I go inside an iframe to perform actions on elements inside an iframe.
I have tried "t.frame("id of iframe")
but it didn't seem to work.

Kindly help.

Kind regards,
Alakai

**Comment by kensoh** [comment]
Hi Alakai, your syntax is correct. Can you share the code and website to replicate this?

**Comment by kensoh** [comment]
Closing issue for time being until further inputs!
