### ISSUE TITLE
Can it automate all apps, is there a control room / orchestrator?

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#85]
user query

---

I have gone through the video if yours on YouTube explaining about digital automation. i found it is interesting. May i know more details on this like can this automate all type of applications like browser,windows, java, mainframe, sap and citrix. and how to schedule bots in this, is there are control room kind of things where i can view all my deployed bots

**Comment by kensoh** [comment]
Thanks for your encouragement.

This tool works best with web applications. It can also automate desktop apps, mainframe, sap and citrix but it does so using computer vision / OCR to visually automate, and using keyboard modifiers and keystrokes. There is no direct access to the application backend to natively read from those apps. For commercial RPA software, for Windows desktop apps, they can have native access to the backend to interact instead of relying on computer vision.

The tool is designed for decentralised implementation of RPA from bottom-up, driven by users directly to solve a pain point in their workflows. It's opposite from commercial RPA tools mainly to be driven centrally by management and to be run on server. Thus there is no control room, orchestrator, or reporting features. Users will have to set up their own scheduled automations on Windows, macOS, Linux, or double click on their scripts to run.

**Comment by EmyEtti00** [comment]
Dear, Sir
My name is Imane and I'm a trainee in a Moroccan company named NOVELIS, the company asked me to do some research about your software TagUI and I will be glad if you could answer some of my questions.
1-Does the software contains an orchestrator if yes how it works?
2- How to manage login and the password?
3- Does the Robot's settings exist?
4- Can I add commands and packages by myself?
 5- how does the software manage to lag?
6- Does TagUI have interactions with desktop apps and java apps?
7-Any information about the WorkQ

**Comment by kensoh** [comment]
Thanks @EmyEtti00 for raising these questions! I'll reply at your same questions at - https://github.com/kelaberetiv/TagUI/issues/1081#issuecomment-911654748
