### ISSUE TITLE
How to get the raw HTML of a webpage? - yes use custom TagUI code

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#91]
user query

**Comment by kensoh** [comment]
I left a backdoor for such use cases. But it's not common digital automation / RPA usage, so I didn't make a function for this. To use this hack do the following -

```py
t.send('dump chrome.getHTML() to tagui_python.txt')
raw_html = t._tagui_output()
```

Above 2 lines will return you the raw html. The send() function is used to send custom TagUI instructions. While the _tagui_output() returns the data dump from TagUI. Both send() and _tagui_output() are more for internal use for this tool, so I don't list them in API reference.

If there are more users raising such edge cases which requires sending custom instructions with send(), I'll put this back to the API reference section. Otherwise clutter the API functions list.

**Comment by kensoh** [comment]
Link to issue #90 which removes send() from readme API reference.

**Comment by jamesmnixon** [comment]
> I left a backdoor for such use cases. But it's not common digital automation / RPA usage, so I didn't make a function for this. To use this hack do the following -
> 
> ```python
> t.send('dump chrome.getHTML() to tagui_python.txt')
> raw_html = t._tagui_output()
> ```
> 
> Above 2 lines will return you the raw html. The send() function is used to send custom TagUI instructions. While the _tagui_output() returns the data dump from TagUI. Both send() and _tagui_output() are more for internal use for this tool, so I don't list them in API reference.
> 
> If there are more users raising such edge cases which requires sending custom instructions with send(), I'll put this back to the API reference section. Otherwise, clutter the API functions list.

It would be nice to be able to edit the HTML of a page and send it back in


Right now I am trying to get around PayPal's re-captcha using 2captcha. I have it all the way through receiving the completed response back from the API, however, the required 'textarea' field is not found not the webpage. I cant get at the HTML because its being run in headless mode to see if its been renames. 

Any thoughts?

**Comment by kensoh** [comment]
Oh, actually no need to use this backdoor of using send(). using `r.read('page')` will do to get the HTML.

From Jupyter notebook or a Python live session, you can do things like `r.read('page')` or `r.snap('page','web.png')` to see the HTML, screenshot or try out different XPaths with r.present() to check things out in the headless browser.

If you want to modify the HTML of the webpage that's doable with `r.dom()`. Simply provide the same code as you would in Chrome inspector console. For eg a recent TagUI issue where a user wants to inject JS code into the webpage to add an ID attribute to a frame -

https://github.com/kelaberetiv/TagUI/issues/1040#issuecomment-848874215

**tagui human language**
```
dom document.querySelector(#viz iframe).id = 'hi5'
```

**rpa for python**
```
r.dom("document.querySelector(#viz iframe).id = 'hi5'")
```

**Comment by jamesmnixon** [comment]
> Oh, actually no need to use this backdoor of using send(). using `r.read('page')` will do to get the HTML.
> 
> From Jupyter notebook or a Python live session, you can do things like `r.read('page')` or `r.snap('page','web.png')` to see the HTML, screenshot or try out different XPaths with r.present() to check things out in the headless browser.
> 
> If you want to modify the HTML of the webpage that's doable with `r.dom()`. Simply provide the same code as you would in Chrome inspector console. For eg a recent TagUI issue where a user wants to inject JS code into the webpage to add an ID attribute to a frame -
> 
> [kelaberetiv/TagUI#1040 (comment)](https://github.com/kelaberetiv/TagUI/issues/1040#issuecomment-848874215)
> 
> **tagui human language**
> 
> ```
> dom document.querySelector(#viz iframe).id = 'hi5'
> ```
> 
> **rpa for python**
> 
> ```
> r.dom("document.querySelector(#viz iframe).id = 'hi5'")
> ```

@kensoh 

After a lot more digging, I think the issue is that the elements I am trying to select are within an Iframe that uses javascript to pull the captcha. I don't think TAGUI is loading the JavaScript within the iframe. therefore tagUI cant find the elements.

When I paste the results from r.read('page') into a file and open as HTML, the Javascript loads and I can see the element I'm looking for. 

Any idea on how to get the iframe JS to load from headless chrome when using tagui?

**Comment by kensoh** [comment]
Hi @jamesmnixon I see, so you are saying for some reason Chrome runs the JS code in normal mode but not in headless mode. That might be possible due to blocking of cross-site code as part of Chrome's security design. If that's the case, then TagUI can't really trigger something so that headless Chrome is forced or authorised to run that JS code in the frame.

The only alternative I can think of is using Xvbf, a virtual framebuffer tool to actually run Chrome in normal mode though there is no real screen. This might get through Chrome's security measure not to run the JS code in the iframe. I have not use xvbf before, though I heard that it is standard method to run Chrome headlessly without going into headless mode.

Below are some starting points to look at if you wish to explore -

https://www.mattzeunert.com/2018/07/21/running-headful-chrome-on-ubuntu-server.html
https://gist.github.com/addyosmani/5336747
http://elementalselenium.com/tips/38-headless

From TagUI side, probably is modifying tagui/src/tagui file the line to run Chrome by inserting xvbf command before that.
