### ISSUE TITLE
[TAGUI][ERROR] - text missing for type() - user usage error

### ISSUE THREAD

**Issue by kensoh** [tebelorg/TagUI-Python#92]
from user @VincentChong123, raised at https://github.com/kelaberetiv/TagUI/issues/640

---

Hi Ken,

Would you please kindly advise on error below? Thanks!
t.type('.gLFyf.gsfi as test google[enter]')
[TAGUI][ERROR] - text missing for type()

`
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import tagui as t
t.init()
True

t.url('https://www.google.com')
True
t.click('.gLFyf.gsfi')
True
t.type()
[TAGUI][ERROR] - target missing for type()
False

 t.type('testing')
[TAGUI][ERROR] - text missing for type()
False

 t.type('.gLFyf.gsfi as test google[enter]')
[TAGUI][ERROR] - text missing for type()
`

tagui chrome automation export result
click .gLFyf.gsfi
type .gLFyf.gsfi as test google[enter]

**Comment by kensoh** [comment]
Hi Vincent, refer to API reference for this Python package -
https://github.com/tebelorg/TagUI-Python#api-reference

The syntax for type() is `t.type(element_identifier, text_to_type)`

**Comment by VincentChong123** [comment]
Hi Ken,

Thanks and corrected as follow
```

import tagui as t
t.init()
t.url('https://www.google.com')
t.click('.gLFyf.gsfi')
t.type('.gLFyf.gsfi', 'test tagui[enter]')
t.close()
```
